source("marketbasketModule.R")
library("shiny")
library("tidyverse")
library("arules")
library("arulesViz")
library("colorspace")
library("visNetwork")
library("plotly")
library("igraph")
library("shinythemes")
library("readxl")
library("DT")
library('knitr')
library('bslib')
options(knitr.kable.NA = '')
ui<- page_fluid(
  marketbasketUI("marketbasket")
)